import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Comfortaa } from "next/font/google"; 
import "./globals.css";

// ⭐️ Import du ThemeProvider
import NavBar from "./NavBar";
import { LanguageProvider } from "./context/LanguageContext";
import { ThemeProvider } from "./context/ThemeProvider"; 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-poppins",
});

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ⭐️ suppressHydrationWarning retiré du <html> et déplacé dans ThemeProvider si nécessaire
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
          ${poppins.variable} ${comfortaa.variable}`}
      >
        {/* ⭐️ ÉTAPE CLÉ : ThemeProvider enveloppe tout */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <LanguageProvider>
                
                <NavBar/>  

                <main className="pt-2"> 
                    {children}
                </main>
            </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}